version: '3'

services:
  postgres:
    image: postgres:12-alpine
    command: postgres -c fsync=off -c synchronous_commit=off -c full_page_writes=off -c random_page_cost=1.0
    environment:
      POSTGRES_DB: test_mock
      POSTGRES_USER: test_mock
      POSTGRES_PASSWORD: test123
    ports:
      - '54320:5432'
    tmpfs: /var/lib/postgresql/data

  redis:
    image: redis:6.2-alpine
    ports:
      - '6380:6379'

networks:
  default:
    name: 'test-server-network'
